language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aserin/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true aserin/docker-react-demo npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-demo"
  env: "Dockerreactdemo-env"
  bucket_name: "elasticbeanstalk-us-east-2-585835609313"
  bucket_path: "docker-react-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY