language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aserin/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true aserin/docker-react-demo npm run test